# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
