# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0002_auto_20180531_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/no-img.jpg', null=True, upload_to='images/%Y-%m-%d'),
        ),
    ]
