# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0003_auto_20180531_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='header',
        ),
    ]
