# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0004_auto_20180531_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
